### ISSUE TITLE
NullPointerException on Headless experiment

### ISSUE THREAD

**Issue by RoiArthurB** [COMOKIT/COMOKIT-Model#26]
Get an error when trying to launch COMOKIT with the GAMA Continuous w/ JDK on a generated XML from COMOKIT-HPC. 

I'm trying to launch the _Headless_ experiment from _Significance of Wearing Masks.gaml_

Here's my log : 
```
$ ./COMOKIT/GAMA/headless/gama-headless.sh ~/COMOKIT/tmp/mask/mask-0.xml ~/COMOKIT/tmp/output
******************************************************************
* GAMA version 1.8                                               *
* http://gama-platform.org                                       *
* (c) 2007-2019 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
> JAI/ImageIO subsystem activated
Number of cpus used:16 (available: 16)
java.lang.NullPointerException
	at com.vividsolutions.jts.geom.Envelope.init(Envelope.java:254)
	at msi.gama.common.geometry.Envelope3D.init(Envelope3D.java:174)
	at msi.gama.common.geometry.Envelope3D.of(Envelope3D.java:75)
	at msi.gaml.operators.Spatial$Creation.envelope(Spatial.java:1408)
	at gaml.additions.GamlAdditions.lambda$413(GamlAdditions.java:470)
	at msi.gaml.expressions.UnaryOperator._value(UnaryOperator.java:84)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gama.runtime.ExecutionScope.evaluate(ExecutionScope.java:499)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:484)
	at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(GamaPopulation.java:441)
	at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(GamaPopulation.java:421)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:121)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:96)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:311)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:265)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:279)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:432)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:149)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:332)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:512)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:154)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:77)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:71)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:247)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:214)
..........
Simulation duration: 69ms
java.lang.NullPointerException
	at com.vividsolutions.jts.geom.Envelope.init(Envelope.java:254)
	at msi.gama.common.geometry.Envelope3D.init(Envelope3D.java:174)
	at msi.gama.common.geometry.Envelope3D.of(Envelope3D.java:75)
	at msi.gaml.operators.Spatial$Creation.envelope(Spatial.java:1408)
	at gaml.additions.GamlAdditions.lambda$413(GamlAdditions.java:470)
	at msi.gaml.expressions.UnaryOperator._value(UnaryOperator.java:84)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gama.runtime.ExecutionScope.evaluate(ExecutionScope.java:499)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:484)
	at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(GamaPopulation.java:441)
	at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(GamaPopulation.java:421)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:121)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:96)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:311)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:265)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:279)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:432)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:149)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:332)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:512)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:154)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:77)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:71)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:247)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:214)
..........
Simulation duration: 2ms
java.lang.NullPointerException
	at com.vividsolutions.jts.geom.Envelope.init(Envelope.java:254)
	at msi.gama.common.geometry.Envelope3D.init(Envelope3D.java:174)
	at msi.gama.common.geometry.Envelope3D.of(Envelope3D.java:75)
	at msi.gaml.operators.Spatial$Creation.envelope(Spatial.java:1408)
	at gaml.additions.GamlAdditions.lambda$413(GamlAdditions.java:470)
	at msi.gaml.expressions.UnaryOperator._value(UnaryOperator.java:84)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gama.runtime.ExecutionScope.evaluate(ExecutionScope.java:499)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:484)
	at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(GamaPopulation.java:441)
	at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(GamaPopulation.java:421)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:121)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:96)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:311)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:265)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:279)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:432)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:149)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:332)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:512)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:154)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:77)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:71)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:247)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:214)
..........
Simulation duration: 1ms
java.lang.NullPointerException
	at com.vividsolutions.jts.geom.Envelope.init(Envelope.java:254)
	at msi.gama.common.geometry.Envelope3D.init(Envelope3D.java:174)
	at msi.gama.common.geometry.Envelope3D.of(Envelope3D.java:75)
	at msi.gaml.operators.Spatial$Creation.envelope(Spatial.java:1408)
	at gaml.additions.GamlAdditions.lambda$413(GamlAdditions.java:470)
	at msi.gaml.expressions.UnaryOperator._value(UnaryOperator.java:84)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gama.runtime.ExecutionScope.evaluate(ExecutionScope.java:499)
	at msi.gaml.variables.Variable.initializeWith(Variable.java:484)
	at msi.gama.metamodel.population.GamaPopulation.createAndUpdateVariablesFor(GamaPopulation.java:441)
	at msi.gama.metamodel.population.GamaPopulation.createVariablesFor(GamaPopulation.java:421)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:121)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:96)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:311)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:265)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:216)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:279)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:432)
	at msi.gama.kernel.experiment.ExperimentScheduler.schedule(ExperimentScheduler.java:149)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:332)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:512)
	at msi.gama.runtime.GAMA.addHeadlessExperiment(GAMA.java:154)
	at msi.gama.headless.core.Experiment.loadCurrentExperiment(Experiment.java:77)
	at msi.gama.headless.core.Experiment.setup(Experiment.java:71)
	at msi.gama.headless.job.ExperimentJob.loadAndBuild(ExperimentJob.java:247)
	at msi.gama.headless.runtime.LocalSimulationRuntime$FakeApplication.run(LocalSimulationRuntime.java:214)
..........
Simulation duration: 1ms
^C
```

and here's the XML : 
```xml
<Experiment_plan>
	<Simulation experiment="Headless" finalStep="10" id="0" seed="125" sourcePath="/root/COMOKIT/COMOKIT-Model/Experiments/Physical Interventions/Significance of Wearing Masks.gaml">
		<Parameters>
			<Parameter name="Proportion wearing mask" type="FLOAT" value="0.5" var="init_all_ages_proportion_wearing_mask" />
			<Parameter name="Factor contact rate" type="FLOAT" value="0.5" var="init_all_ages_factor_contact_rate_wearing_mask" />
			<Parameter type="INT" value="125" var="idSimulation" />
			<Parameter type="STRING" value="/root/COMOKIT/batch_output/init_all_ages_proportion_wearing_mask_0.5-init_all_ages_factor_contact_rate_wearing_mask_0.5" var="result_folder" />
		</Parameters>
		<Outputs />
	</Simulation>

	[...]

</Experiment_plan>
```

**Comment by AlexisDrogoul** [comment]
Should be fixed after https://github.com/gama-platform/gama/issues/2983 has been solved.
